kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ocaz-cli
  namespace: sealed-secrets
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "ocazcli:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: "ubi8:latest"
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/michaelshire/ocazcli.git"
    contextDir: ocazcli
  runPolicy: Serial
