kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: sealingsecrettoakv
  namespace: sealed-secrets
spec:
  schedule: "0 5 */15 * *"
  parallelism: 1
  completions: 1
  backoffLimit: 1
  jobTemplate:
    metadata:
      name: backupsealinsecret
    spec:
      template:
        spec:
          serviceAccountName: sealed-secret-sync
          containers:
            - name: ocaztool
              image: 'image-registry.openshift-image-registry.svc:5000/sealed-secrets/ocazcli:latest'
              command:
                - /bin/sh
                - '-c'
              args:
                - oc get secret -l sealedsecrets.bitnami.com/sealed-secrets-key=active -n sealed-secrets -o yaml --token=`cat /var/run/secrets/kubernetes.io/serviceaccount/token` --server=https://api.mj0pbxvw.westus2.aroapp.io:6443 >> /tmp/secretkey.yaml &&
                  az login --service-principal -u `cat /tmp/aztoken/serviceprincipal` -p `cat /tmp/aztoken/token` --tenant `cat /tmp/aztoken/aztenant`
                  az keyvault secret set --name sealed-secret-key --vault-name `cat /tmp/aztoken/azkeyvaultname` --subscription `cat /tmp/aztoken/azsubscription` -f /tmp/secretkey.yaml
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
              volumeMounts:
              - name: aztoken
                readOnly: true
                mountPath: /tmp/aztoken
          volumes:
          - name: aztoken
            secret:
              secretName: sealed-secrets-akvtoken
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
