kind: Job
apiVersion: batch/v1
metadata:
  name: testing
  namespace: sealed-secrets
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      name: octest
    spec:
      serviceAccountName: sealed-secret-sync
      containers:
        - name: octest
          image: 'image-registry.openshift-image-registry.svc:5000/sealed-secrets/ocazcli:latest'
          command:
            - /bin/sh
            - '-c'
          args:
            - oc get secret -l sealedsecrets.bitnami.com/sealed-secrets-key=active -n sealed-secrets -o yaml --token=`cat /var/run/secrets/kubernetes.io/serviceaccount/token` --server=https://api.mj0pbxvw.westus2.aroapp.io:6443 >> /tmp/secretkey.yaml &&
              az login --service-principal -u 56abc7a3-7876-475d-9758-40e9b6f2b539 -p `cat /tmp/aztoken/token` --tenant 1aa51068-11a6-4bd2-8646-1fff31a30ffc &&
              az keyvault secret set --name sealed-secret-key --vault-name arodevarmkeyus2001 --subscription SuncorContainer-DEV -f /tmp/secretkey.yaml
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          volumeMounts:
          - name: aztoken
            readOnly: true
            mountPath: /tmp/aztoken
      volumes:
      - name: aztoken
        secret:
          secretName: sealed-secrets-akvtoken
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
