kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secret-rb
  namespace: sealed-secrets
subjects:
  - kind: ServiceAccount
    name: sealed-secret-sync
    namespace: sealed-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secret-reader
