kind: Secret
apiVersion: v1
metadata:
  name: sealed-secrets-akvtoken
  namespace: sealed-secrets
data:
  aztenant: <Base64 encoded aztenant ID (not name)>
  serviceprincipal: <base64 encoded service principal ID (not name)>
  azsubscription: <Base64 encoded subscription name>
  azkeyvaultname: <Base64 encoded vault name>
  token: <Base64 encoded Azure Key Vault SP token>
type: Opaque
